"""Shared contract exports."""

from cdl_api.contracts.auth import LoginRequest, LoginResponse, LogoutResponse
from cdl_api.contracts.common import (
    ApiErrorResponse,
    ErrorCode,
    RuleReference,
    ValidationErrorResponse,
)
from cdl_api.contracts.domain import (
    FixtureSummary,
    GameweekSummary,
    PlayerSummary,
    TeamSummary,
)
from cdl_api.contracts.league_models import (
    FixtureDetailResponse,
    FixtureScore,
    FixtureStatus,
    HeadToHeadResponse,
    KnockoutResponse,
    LeagueFixture,
    LeagueFixturesResponse,
    LeagueTableResponse,
)
from cdl_api.contracts.rules_models import (
    RuleCategory,
    RuleSection,
    RulesIndexResponse,
    RuleVersion,
)
from cdl_api.contracts.session import SessionState, SessionUser
from cdl_api.contracts.squad import (
    InterestCreateRequest,
    InterestDeleteResponse,
    InterestResponse,
    PlayerDetail,
    PlayerMetric,
    PlayerOwnershipStatus,
    PlayerPosition,
    ScoutingFilters,
    ScoutingPlayersResponse,
    SquadSummaryResponse,
    TradeAsset,
    TradeCreateRequest,
    TradeProposal,
    TradesResponse,
    TradeStatus,
    TradeUpdateRequest,
)
from cdl_api.contracts.theme import ThemePreset, UserPreferences

__all__ = [
    "ApiErrorResponse",
    "ErrorCode",
    "FixtureDetailResponse",
    "FixtureScore",
    "FixtureStatus",
    "FixtureSummary",
    "GameweekSummary",
    "HeadToHeadResponse",
    "InterestCreateRequest",
    "InterestDeleteResponse",
    "InterestResponse",
    "KnockoutResponse",
    "LeagueFixture",
    "LeagueFixturesResponse",
    "LeagueTableResponse",
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "PlayerDetail",
    "PlayerMetric",
    "PlayerOwnershipStatus",
    "PlayerPosition",
    "PlayerSummary",
    "RuleCategory",
    "RuleReference",
    "RuleSection",
    "RulesIndexResponse",
    "RuleVersion",
    "ScoutingFilters",
    "ScoutingPlayersResponse",
    "SessionState",
    "SessionUser",
    "SquadSummaryResponse",
    "TeamSummary",
    "ThemePreset",
    "TradeAsset",
    "TradeCreateRequest",
    "TradeProposal",
    "TradesResponse",
    "TradeStatus",
    "TradeUpdateRequest",
    "UserPreferences",
    "ValidationErrorResponse",
]
